format = '$all'

# Disable newline between prompts
add_newline = false

[shell]
disabled = false

[conda]
format = '[$symbol$environment](dimmed green) '

[python]
symbol = 'ðŸ‘¾ '
pyenv_version_name = true
# Only use the `python3` binary to get the version.
python_binary = 'python3'
# Don't trigger for files with the py extension
detect_extensions = []

[git_branch]
symbol = 'ðŸŒ±'
truncation_length = 4
truncation_symbol = ''
ignore_branches = ['']

[git_commit]
commit_hash_length = 4
tag_symbol = 'ðŸ”– '
